### ISSUE TITLE
Forcing restart of process?

### ISSUE THREAD

**Issue by MilesCranmer** [julia-vscode/TestItemRunner.jl#73] opened 2024-06-17 21:44 UTC
Just wondering how to restart the VSCode Julia process for testing? For example if I add a new dependency; how can I restart Julia? (Right now I have to reload the VSCode window which seems to achieve this)

**Comment by davidanthoff** [comment] 2024-06-18 09:35
The problem is a duplicate of https://github.com/julia-vscode/julia-vscode/issues/3022. That issue is fixed in https://github.com/julia-vscode/julia-vscode/pull/3609, but that is still a bit away from being ready.

You _can_ terminate any test process from the Julia Workspace view. But that won't solve the underlying problem, as we still have a cache of the outdated env hanging around, so even the restarted test process will not be correct. Until I merge that PR mentioned above, you'll have to restart VS Code whenever anything changes in the env...

**Closed by davidanthoff** 2024-06-18 09:35 UTC
